### ISSUE TITLE
Exception in ssl.py then timeouts

### ISSUE THREAD

**Issue by jkbrzt** [kevin1024/pytest-httpbin#32]
I'm getting some failures on OSX and Homebrew-installed Python 2 and 3 on Travis CI. I haven't been able to reproduce it locally. It seems to only happen every ca third build on Travis.

First there's an exception in `ssl.py` after which all the subsequent HTTPS request time out:

```python
tests/test_ssl.py::TestClientSSLCertHandling::test_cert_file_invalid PASSED
tests/test_ssl.py::TestClientSSLCertHandling::test_cert_ok_but_missing_key ----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 49299)
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/Users/travis/build/jkbrzt/httpie/.tox/py27/lib/python2.7/site-packages/pytest_httpbin/serve.py", line 68, in finish_request
    server_side=True
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 911, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 579, in __init__
PASSED
tests/test_ssl.py::TestClientSSLCertHandling::test_cert_and_key FAILED
tests/test_ssl.py::TestClientSSLCertHandling::test_cert_pem FAILED
tests/test_ssl.py::TestServerSSLCertHandling::test_self_signed_server_cert_by_default_raises_ssl_error FAILED
tests/test_ssl.py::TestServerSSLCertHandling::test_verify_no_OK FAILED
tests/test_ssl.py::TestServerSSLCertHandling::test_verify_custom_ca_bundle_path FAILED
tests/test_ssl.py::TestServerSSLCertHandling::test_verify_custom_ca_bundle_invalid_path FAILED
tests/test_ssl.py::TestServerSSLCertHandling::test_verify_custom_ca_bundle_invalid_bundle FAILED
tests/test_stream.py::TestStream::test_pretty_redirected_stream PASSED
```

And a bit further down it shows that the requests in the failing tests timed out:

```python
_________________ TestClientSSLCertHandling.test_cert_and_key __________________
Traceback (most recent call last):
  File "/Users/travis/build/jkbrzt/httpie/tests/test_ssl.py", line 47, in test_cert_and_key
    '--cert-key', CLIENT_KEY)
  File "/Users/travis/build/jkbrzt/httpie/tests/utils.py", line 214, in http
    raise Exception('Unexpected exit status: %s', exit_status)
Exception: ('Unexpected exit status: %s', 2)
----------------------------- Captured stderr call -----------------------------
http: error: Request timed out (30s).

…
```

Complete output: https://travis-ci.org/jkbrzt/httpie/builds/112886254
The source code of the failing tests: https://github.com/jkbrzt/httpie/blob/master/tests/test_ssl.py
Details about the environment: https://docs.travis-ci.com/user/osx-ci-environment/

I believe it runs on Mavericks.

**Comment by kevin1024** [comment]
Whoah that sounds hard to track down. I'll see what I can do.

**Comment by kevin1024** [comment]
I am completely failing to reproduce this.  It looks like the `test_cert_ok_but_missing_key` kills the server (I think it's throwing an SSLError) and then the following tests don't have a server to execute against.

Just trying to get the server to die locally...

**Comment by kevin1024** [comment]
OK I pushed a new fix and release that might resolve the issue.  Give it a try and let me know @jkbrzt

**Comment by jkbrzt** [comment]
So far so good (https://travis-ci.org/jkbrzt/httpie).

Thanks for looking into it!

**Comment by kevin1024** [comment]
Crossing fingers super hard :pray:

**Comment by jkbrzt** [comment]
It's failed again :sob: 

https://travis-ci.org/jkbrzt/httpie/jobs/113018186

```
tests/test_ssl.py::TestClientCert::test_cert_ok_but_missing_key PASSEDattempting to ignore so the rest of the tests can run
----------------------------------------
tests/test_ssl.py::TestClientCert::test_cert_and_key FAILED
tests/test_ssl.py::TestClientCert::test_cert_pem FAILED
tests/test_ssl.py::TestServerCert::test_self_signed_server_cert_by_default_raises_ssl_error FAILED
tests/test_ssl.py::TestServerCert::test_verify_no_OK FAILED
tests/test_ssl.py::TestServerCert::test_verify_custom_ca_bundle_path FAILED
tests/test_ssl.py::TestServerCert::test_verify_custom_ca_bundle_invalid_path FAILED
tests/test_ssl.py::TestServerCert::test_verify_custom_ca_bundle_invalid_bundle FAILED
tests/test_stream.py::TestStream::test_pretty_redirected_stream PASSED
```

```
=================================== FAILURES ===================================
_______________________ TestClientCert.test_cert_and_key _______________________
Traceback (most recent call last):
  File "/Users/travis/build/jkbrzt/httpie/tests/test_ssl.py", line 47, in test_cert_and_key
    '--cert-key', CLIENT_KEY)
  File "/Users/travis/build/jkbrzt/httpie/tests/utils.py", line 219, in http
    raise Exception('Unexpected exit status: %s', exit_status)
Exception: ('Unexpected exit status: %s', 2)
---------------------------- Captured stdout setup -----------------------------
pytest-httpbin server hit an exception serving request: EOF occurred in violation of protocol (_ssl.c:645)
----------------------------- Captured stderr call -----------------------------
Exception in thread <class 'pytest_httpbin.serve.SecureServer'>:
Traceback (most recent call last):
  File "/Users/travis/build/jkbrzt/httpie/.tox/py35/lib/python3.5/site-packages/pytest_httpbin/serve.py", line 69, in finish_request
    server_side=True
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 1064, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 747, in __init__
    self.do_handshake()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 983, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ssl.py", line 628, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLEOFError: EOF occurred in violation of protocol (_ssl.c:645)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 344, in process_request
    self.finish_request(request, client_address)
  File "/Users/travis/build/jkbrzt/httpie/.tox/py35/lib/python3.5/site-packages/pytest_httpbin/serve.py", line 74, in finish_request
    print("attempting to ignore so the rest of the tests can run")
OSError: [Errno 9] Bad file descriptor
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 239, in serve_forever
    self._handle_request_noblock()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 320, in _handle_request_noblock
    self.handle_error(request, client_address)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socketserver.py", line 373, in handle_error
    print('-'*40)
OSError: [Errno 9] Bad file descriptor
http: error: Request timed out (3.0s).
_________________________ TestClientCert.test_cert_pem _________________________
Traceback (most recent call last):
  File "/Users/travis/build/jkbrzt/httpie/tests/test_ssl.py", line 53, in test_cert_pem
    '--cert', CLIENT_PEM)
  File "/Users/travis/build/jkbrzt/httpie/tests/utils.py", line 219, in http
    raise Exception('Unexpected exit status: %s', exit_status)
Exception: ('Unexpected exit status: %s', 2)
----------------------------- Captured stderr call -----------------------------
http: error: Request timed out (3.0s).
```

**Comment by kevin1024** [comment]
Hmm, at least this time I have a little more to go by thanks to that print I jammed in there.

**Comment by kevin1024** [comment]
OK, still no luck reproducing this problem, but I just pushed another release that might help.

**Comment by jkbrzt** [comment]
Great! I'll keep an eye on the issue and will report if it occurs again. Thanks 👍
