### ISSUE TITLE
Doesn't work with httpbin 0.10.1

### ISSUE THREAD

**Issue by AdamWill** [kevin1024/pytest-httpbin#83]
It's been requested that the Fedora httpbin package be updated - https://src.fedoraproject.org/rpms/python-httpbin/pull-request/3 - but I just tested building pytest-httpbin 2.0.0 against httpbin 0.10.1, and most of the test suite fails. It seems like the httpbin server keeps returning 500 errors instead of working, but the test output doesn't make it clear why it's not working, I just get a lot of failures like this:

    ________________________ TestClassBassedTests.test_http ________________________

    self = <test_httpbin.TestClassBassedTests testMethod=test_http>

        def test_http(self):
    >       assert requests.get(self.httpbin.url + "/get").status_code == 200
    E       AssertionError: assert 500 == 200
    E        +  where 500 = <Response [500]>.status_code
    E        +    where <Response [500]> = <function get at 0x7fc5556b2160>(('http://127.0.0.1:42169' + '/get'))
    E        +      where <function get at 0x7fc5556b2160> = requests.get
    E        +      and   'http://127.0.0.1:42169' = <pytest_httpbin.serve.Server object at 0x7fc55617fb90>.url
    E        +        where <pytest_httpbin.serve.Server object at 0x7fc55617fb90> = <test_httpbin.TestClassBassedTests testMethod=test_http>.httpbin

    tests/test_httpbin.py:66: AssertionError
    ----------------------------- Captured stderr call -----------------------------
    127.0.0.1 - - [17/Oct/2023 18:19:45] "GET /get HTTP/1.1" 500 265
    ------------------------------ Captured log call -------------------------------
    ERROR    httpbin.core:app.py:1744 Exception on /get [GET]
    Traceback (most recent call last):
      File "/usr/lib/python3.12/site-packages/flask/app.py", line 2529, in wsgi_app
        response = self.full_dispatch_request()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/flask/app.py", line 1825, in full_dispatch_request
        rv = self.handle_user_exception(e)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/flask/app.py", line 1823, in full_dispatch_request
        rv = self.dispatch_request()
             ^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/flask/app.py", line 1799, in dispatch_request
        return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/httpbin/core.py", line 394, in view_get
        return jsonify(get_dict("url", "args", "headers", "origin"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/httpbin/core.py", line 81, in jsonify
        response = flask_jsonify(*args, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/flask/json/__init__.py", line 342, in jsonify
        return current_app.json.response(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.12/site-packages/flask/json/provider.py", line 281, in response
        warnings.warn(
    DeprecationWarning: The 'JSONIFY_PRETTYPRINT_REGULAR' config key is deprecated and will be removed in Flask 2.3. Set 'app.json.compact' instead.

it doesn't seem like the DeprecationWarning should be the problem as it's just a warning, but...I'm not sure. If I build pytest-httpbin against httpbin 0.7.0 (patched a bit to deal with the werkzeug 2.1 issue and stuff), all the tests pass.

**Comment by AdamWill** [comment]
oh, hum. seems like it *is* the Flask deprecation warning that's the issue, if I patch that out of httpbin, the tests pass. Weird that it blows up on a warning, but never mind.
